-- BYOSE Market Supabase bootstrap
-- Run this in the Supabase SQL editor before switching runtime writes to Supabase.
-- The current project is reachable with the publishable key, but writes are blocked by RLS,
-- the products storage bucket does not exist, and the existing public schema does not match
-- the storefront/admin product payload shape.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  catalog_id bigint generated by default as identity unique,
  name text not null default '',
  title text not null default '',
  description text not null default '',
  short_description text not null default '',
  long_description jsonb not null default '[]'::jsonb,
  badge text not null default '',
  category text not null default 'general',
  price numeric(12,2) not null default 0,
  old_price numeric(12,2) not null default 0,
  stock integer not null default 0,
  image text not null default '',
  main_image text not null default '',
  gallery jsonb not null default '[]'::jsonb,
  keywords jsonb not null default '[]'::jsonb,
  highlights jsonb not null default '[]'::jsonb,
  trust jsonb not null default '[]'::jsonb,
  specs jsonb not null default '[]'::jsonb,
  attributes jsonb not null default '[]'::jsonb,
  variants jsonb not null default '{}'::jsonb,
  visibility text not null default 'both',
  priority integer not null default 0,
  order_index integer not null default 0,
  highlight_tag text not null default '',
  status text not null default 'active',
  page text not null default 'product-details1.html',
  url text not null default '',
  main_image_storage_path text not null default '',
  gallery_storage_paths jsonb not null default '[]'::jsonb,
  extra_info jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  customer_code text unique,
  name text not null default '',
  email text not null default '',
  phone text not null default '',
  password_hash text not null default '',
  avatar text not null default '',
  role text not null default 'customer',
  status text not null default 'active',
  verified boolean not null default false,
  address jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_id text unique not null,
  user_id text not null default '',
  customer_id text not null default '',
  customer_name text not null default '',
  customer_email text not null default '',
  customer_phone text not null default '',
  status text not null default 'Pending',
  order_status text not null default 'pending',
  payment_status text not null default 'pending',
  payment_status_label text not null default 'Pending',
  payment_method text not null default '',
  payment_type text not null default '',
  note text not null default '',
  subtotal numeric(12,2) not null default 0,
  shipping_fee numeric(12,2) not null default 0,
  delivery_fee numeric(12,2) not null default 0,
  cod_fee numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  total_amount numeric(12,2) not null default 0,
  total_price numeric(12,2) not null default 0,
  delivery_method text not null default '',
  delivery_label text not null default '',
  items jsonb not null default '[]'::jsonb,
  products jsonb not null default '[]'::jsonb,
  shipping_address jsonb not null default '{}'::jsonb,
  full_address jsonb not null default '{}'::jsonb,
  gps_location jsonb not null default '{}'::jsonb,
  payment jsonb not null default '{}'::jsonb,
  customer jsonb not null default '{}'::jsonb,
  status_history jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cart_items (
  id uuid primary key default gen_random_uuid(),
  cart_id uuid not null default gen_random_uuid(),
  user_id text not null default '',
  product_id text not null default '',
  quantity integer not null default 1,
  attributes jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.visits (
  id uuid primary key default gen_random_uuid(),
  client_activity_id text not null default '',
  user_id text not null default '',
  session_id text not null default '',
  event_type text not null default 'visit',
  path text not null default '',
  referrer text not null default '',
  user_agent text not null default '',
  device text not null default '',
  ip text not null default '',
  city text not null default '',
  country text not null default '',
  org text not null default '',
  duration integer not null default 0,
  meta jsonb not null default '{}'::jsonb,
  started_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.visitors (
  id uuid primary key default gen_random_uuid(),
  visitor_key text not null default '',
  user_id text not null default '',
  session_id text not null default '',
  path text not null default '',
  referrer text not null default '',
  user_agent text not null default '',
  device text not null default '',
  country text not null default '',
  city text not null default '',
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_reviews (
  id uuid primary key default gen_random_uuid(),
  product_catalog_id bigint not null,
  user_id text not null default '',
  customer_name text not null default '',
  rating integer not null default 5,
  title text not null default '',
  review text not null default '',
  status text not null default 'published',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_status_idx on public.products(status, order_index desc, updated_at desc);
create index if not exists products_category_idx on public.products(category, visibility, status, updated_at desc);
create index if not exists orders_created_idx on public.orders(created_at desc, updated_at desc);
create index if not exists cart_items_user_idx on public.cart_items(user_id, updated_at desc);
create index if not exists visits_event_idx on public.visits(event_type, created_at desc);
create index if not exists visitors_created_idx on public.visitors(created_at desc);
create index if not exists product_reviews_product_idx on public.product_reviews(product_catalog_id, created_at desc);

drop trigger if exists set_products_updated_at on public.products;
create trigger set_products_updated_at before update on public.products for each row execute function public.set_updated_at();

drop trigger if exists set_users_updated_at on public.users;
create trigger set_users_updated_at before update on public.users for each row execute function public.set_updated_at();

drop trigger if exists set_orders_updated_at on public.orders;
create trigger set_orders_updated_at before update on public.orders for each row execute function public.set_updated_at();

drop trigger if exists set_cart_items_updated_at on public.cart_items;
create trigger set_cart_items_updated_at before update on public.cart_items for each row execute function public.set_updated_at();

drop trigger if exists set_visits_updated_at on public.visits;
create trigger set_visits_updated_at before update on public.visits for each row execute function public.set_updated_at();

drop trigger if exists set_visitors_updated_at on public.visitors;
create trigger set_visitors_updated_at before update on public.visitors for each row execute function public.set_updated_at();

drop trigger if exists set_product_reviews_updated_at on public.product_reviews;
create trigger set_product_reviews_updated_at before update on public.product_reviews for each row execute function public.set_updated_at();

alter table public.products enable row level security;
alter table public.users enable row level security;
alter table public.orders enable row level security;
alter table public.cart_items enable row level security;
alter table public.visits enable row level security;
alter table public.visitors enable row level security;
alter table public.product_reviews enable row level security;

drop policy if exists products_select_public on public.products;
create policy products_select_public on public.products for select using (true);

drop policy if exists products_write_public on public.products;
create policy products_write_public on public.products for all using (true) with check (true);

drop policy if exists users_read_write_public on public.users;
create policy users_read_write_public on public.users for all using (true) with check (true);

drop policy if exists orders_read_write_public on public.orders;
create policy orders_read_write_public on public.orders for all using (true) with check (true);

drop policy if exists cart_items_read_write_public on public.cart_items;
create policy cart_items_read_write_public on public.cart_items for all using (true) with check (true);

drop policy if exists visits_read_write_public on public.visits;
create policy visits_read_write_public on public.visits for all using (true) with check (true);

drop policy if exists visitors_read_write_public on public.visitors;
create policy visitors_read_write_public on public.visitors for all using (true) with check (true);

drop policy if exists product_reviews_read_write_public on public.product_reviews;
create policy product_reviews_read_write_public on public.product_reviews for all using (true) with check (true);

insert into storage.buckets (id, name, public)
select 'products', 'products', true
where not exists (
  select 1 from storage.buckets where id = 'products'
);

drop policy if exists products_bucket_read_public on storage.objects;
create policy products_bucket_read_public on storage.objects
for select
using (bucket_id = 'products');

drop policy if exists products_bucket_write_public on storage.objects;
create policy products_bucket_write_public on storage.objects
for all
using (bucket_id = 'products')
with check (bucket_id = 'products');