#!/usr/bin/env bash
#
# Configure nginx to serve /uploads/* from the persistent uploads directory and
# verify that a real on-disk product image is publicly reachable.
#
# Run on the VPS as root:
#   cd /root/byose-market && bash scripts/fix-vps-uploads-serving.sh
#   # legacy path still supported: /root/BYOSESEMARKET4
#
set -euo pipefail

if [[ -z "${DEPLOY_DIR:-}" ]]; then
  if [[ -d "/root/byose-market" ]]; then
    DEPLOY_DIR="/root/byose-market"
  elif [[ -d "/root/BYOSESEMARKET4" ]]; then
    DEPLOY_DIR="/root/BYOSESEMARKET4"
  else
    DEPLOY_DIR="/root/byose-market"
  fi
fi
UPLOADS_DIR="${UPLOADS_DIR:-/var/lib/byosemarket/uploads}"
NGINX_SITE="${NGINX_SITE:-/etc/nginx/sites-available/byosemarket}"
NGINX_ENABLED="${NGINX_ENABLED:-/etc/nginx/sites-enabled/byosemarket}"
NGINX_SNIPPET="${NGINX_SNIPPET:-/etc/nginx/snippets/byosemarket-uploads.conf}"
API_PORT="${API_PORT:-5000}"
NGINX_VERIFY_HOST="${NGINX_VERIFY_HOST:-127.0.0.1}"
PUBLIC_VERIFY_HOST="${PUBLIC_VERIFY_HOST:-byosemarket.com}"

log() {
  printf '[fix-uploads] %s\n' "$*"
}

warn() {
  printf '[fix-uploads] WARNING: %s\n' "$*" >&2
}

fail() {
  printf '[fix-uploads] ERROR: %s\n' "$*" >&2
  exit 1
}

remove_conflicting_byosemarket_sites() {
  local candidate
  shopt -s nullglob
  for candidate in /etc/nginx/sites-enabled/* /etc/nginx/conf.d/*.conf; do
    [[ "${candidate}" == "${NGINX_ENABLED}" ]] && continue
    if [[ -f "${candidate}" ]] && grep -Eq 'server_name[^;]*(byosemarket\.com|www\.byosemarket\.com)' "${candidate}"; then
      log "Removing stale Byose Market nginx config: ${candidate}"
      rm -f "${candidate}"
    fi
  done
  shopt -u nullglob
}

if [[ "${EUID}" -ne 0 ]]; then
  fail "Run as root: sudo bash scripts/fix-vps-uploads-serving.sh"
fi

if [[ ! -d "${DEPLOY_DIR}" ]]; then
  fail "Deploy directory not found: ${DEPLOY_DIR}"
fi

if [[ -f "${DEPLOY_DIR}/scripts/migrate-production-uploads.sh" ]]; then
  bash "${DEPLOY_DIR}/scripts/migrate-production-uploads.sh"
else
  mkdir -p "${UPLOADS_DIR}/products" "${UPLOADS_DIR}/categories" "${UPLOADS_DIR}/users" "${UPLOADS_DIR}/reviews" "${UPLOADS_DIR}/hero" "${UPLOADS_DIR}/temp"
  chmod -R u+rwX,go+rX "${UPLOADS_DIR}"
fi

product_count="$(find "${UPLOADS_DIR}/products" -type f ! -name '.gitkeep' 2>/dev/null | wc -l | tr -d ' ')"
hero_count="$(find "${UPLOADS_DIR}/hero" -type f ! -name '.gitkeep' 2>/dev/null | wc -l | tr -d ' ')"
log "Product image files on disk: ${product_count}"
log "Hero image files on disk: ${hero_count}"

if [[ "${product_count}" -eq 0 ]]; then
  warn "No product images in ${UPLOADS_DIR}/products yet; HTTP verification will be skipped."
fi

if [[ "${hero_count}" -eq 0 ]]; then
  warn "No hero images in ${UPLOADS_DIR}/hero yet; hero HTTP verification will be skipped."
fi

if ! command -v nginx >/dev/null 2>&1; then
  fail "nginx is not installed."
fi

mkdir -p /etc/nginx/snippets

log "Installing uploads nginx snippet for ${UPLOADS_DIR}..."
cat > "${NGINX_SNIPPET}" <<NGINX
# Generated by fix-vps-uploads-serving.sh — do not edit manually on the server.
location ^~ /uploads/ {
    alias ${UPLOADS_DIR}/;
    access_log off;
    expires 30d;
    add_header Cache-Control "public, max-age=2592000, stale-while-revalidate=86400" always;
    add_header X-Content-Type-Options "nosniff" always;
    open_file_cache max=2000 inactive=60s;
    open_file_cache_valid 30s;
    open_file_cache_min_uses 2;
    open_file_cache_errors off;
    types {
        image/jpeg  jpg jpeg;
        image/png   png;
        image/webp  webp;
        image/gif   gif;
        image/avif  avif;
    }
    default_type application/octet-stream;
}
NGINX

if [[ -f "${DEPLOY_DIR}/deploy/nginx-snippet-static-assets.conf" ]]; then
  log "Installing static assets nginx snippet..."
  install -m 644 "${DEPLOY_DIR}/deploy/nginx-snippet-static-assets.conf" /etc/nginx/snippets/byosemarket-static-assets.conf
fi

log "Ensuring root storefront JavaScript and CSS are published..."
if [[ -d "${WEB_ROOT:-/var/www/byosemarket}" ]]; then
  for file in "${DEPLOY_DIR}"/*.js; do
    if [[ -f "${file}" ]]; then
      cp -f "${file}" "${WEB_ROOT:-/var/www/byosemarket}/$(basename "${file}")"
    fi
  done

  for file in "${DEPLOY_DIR}"/*.css; do
    if [[ -f "${file}" ]]; then
      cp -f "${file}" "${WEB_ROOT:-/var/www/byosemarket}/$(basename "${file}")"
    fi
  done
fi

log "Installing nginx site config (HTTP + HTTPS with /uploads alias)..."
install -m 644 "${DEPLOY_DIR}/deploy/nginx-byosemarket.conf" "${NGINX_SITE}"
ln -sfn "${NGINX_SITE}" "${NGINX_ENABLED}"
remove_conflicting_byosemarket_sites

if [[ -f /etc/nginx/sites-enabled/default ]]; then
  rm -f /etc/nginx/sites-enabled/default
fi

log "Testing nginx configuration..."
nginx -t

log "Reloading nginx..."
systemctl reload nginx

resolve_sample_disk_file() {
  find "${UPLOADS_DIR}/products" -type f ! -name '.gitkeep' 2>/dev/null | head -n 1
}

resolve_api_sample_path() {
  curl -fsS "http://127.0.0.1:${API_PORT}/api/products" 2>/dev/null | node -e "
    let raw = '';
    process.stdin.on('data', (chunk) => { raw += chunk; });
    process.stdin.on('end', () => {
      try {
        const payload = JSON.parse(raw);
        const products = Array.isArray(payload.products) ? payload.products : [];
        const product = products.find((entry) => String(entry.mainImage || entry.image || '').includes('/uploads/products/'));
        const value = String(product?.mainImage || product?.image || '').trim();
        if (!value) process.exit(2);
        const path = value.startsWith('http') ? new URL(value).pathname : value;
        process.stdout.write(path);
      } catch (_error) {
        process.exit(1);
      }
    });
  " 2>/dev/null || true
}

probe_upload_url() {
  local label="$1"
  local base_url="$2"
  local sample_path="$3"
  local headers_file http_code content_type

  headers_file="$(mktemp)"
  http_code="$(curl -sS -o /dev/null -D "${headers_file}" -w "%{http_code}" --max-time 15 "${base_url}${sample_path}" || printf '000')"
  content_type="$(awk -F': ' 'tolower($1)=="content-type" {print tolower($2)}' "${headers_file}" | tr -d '\r' | head -n 1)"
  rm -f "${headers_file}"

  printf '%s\n' "${http_code}|${content_type}|${label}|${base_url}${sample_path}"
}

verify_upload_routes() {
  local sample_file sample_path relative_path disk_path api_sample_path

  sample_file="$(resolve_sample_disk_file || true)"
  if [[ -z "${sample_file}" ]]; then
    warn "No on-disk product image available; skipping HTTP upload verification."
    return 0
  fi

  sample_path="/uploads/products/$(basename "${sample_file}")"
  relative_path="${sample_path#/uploads/}"
  disk_path="${UPLOADS_DIR}/${relative_path}"

  log "Verification sample (disk-first): ${sample_path}"
  log "Expected disk path: ${disk_path}"

  if [[ ! -f "${disk_path}" ]]; then
    warn "Sample file is missing on disk; skipping HTTP upload verification."
    return 0
  fi

  api_sample_path="$(resolve_api_sample_path)"
  if [[ -n "${api_sample_path}" && "${api_sample_path}" != "${sample_path}" ]]; then
    api_relative="${api_sample_path#/uploads/}"
    api_disk_path="${UPLOADS_DIR}/${api_relative}"
    if [[ ! -f "${api_disk_path}" ]]; then
      warn "API references ${api_sample_path} but that file is missing on disk (stale DB reference)."
      warn "Using on-disk sample ${sample_path} instead of failing deployment."
    fi
  fi

  local probe result http_code content_type label url
  local -a probes=(
    "nginx|http://${NGINX_VERIFY_HOST}"
    "api|http://127.0.0.1:${API_PORT}"
  )

  for probe in "${probes[@]}"; do
    label="${probe%%|*}"
    url="${probe#*|}"
    result="$(probe_upload_url "${label}" "${url}" "${sample_path}")"
    IFS='|' read -r http_code content_type _ full_url <<< "${result}"

    log "${label} probe: ${full_url} -> HTTP ${http_code}, Content-Type: ${content_type:-unknown}"

    if [[ "${http_code}" != "200" ]]; then
      fail "${label} upload route returned HTTP ${http_code} for ${sample_path} (expected 200). Disk file exists at ${disk_path}."
    fi

    if [[ "${content_type}" != image/* ]]; then
      fail "${label} upload route returned '${content_type:-unknown}' instead of image/* for ${sample_path}"
    fi

    log "${label} upload route OK (${content_type})"
  done

  if curl -fsSI "https://${PUBLIC_VERIFY_HOST}${sample_path}" >/dev/null 2>&1; then
    result="$(probe_upload_url "https" "https://${PUBLIC_VERIFY_HOST}" "${sample_path}")"
    IFS='|' read -r http_code content_type _ full_url <<< "${result}"
    log "https probe: ${full_url} -> HTTP ${http_code}, Content-Type: ${content_type:-unknown}"
    if [[ "${http_code}" == "200" && "${content_type}" == image/* ]]; then
      log "HTTPS upload route OK (${content_type})"
    else
      warn "HTTPS upload route check did not return image/* (HTTP ${http_code})."
    fi
  else
    log "HTTPS verification skipped (domain or certificate unavailable from this host)."
  fi

  # Optional hero-bucket probe (UUID files, same /uploads location rules).
  local hero_file hero_path
  hero_file="$(find "${UPLOADS_DIR}/hero" -type f ! -name '.gitkeep' 2>/dev/null | head -n 1 || true)"
  if [[ -n "${hero_file}" ]]; then
    hero_path="/uploads/hero/$(basename "${hero_file}")"
    result="$(probe_upload_url "hero-nginx" "http://${NGINX_VERIFY_HOST}" "${hero_path}")"
    IFS='|' read -r http_code content_type _ full_url <<< "${result}"
    log "hero probe: ${full_url} -> HTTP ${http_code}, Content-Type: ${content_type:-unknown}"
    if [[ "${http_code}" != "200" || "${content_type}" != image/* ]]; then
      fail "Hero upload route returned HTTP ${http_code} / '${content_type:-unknown}' for ${hero_path}"
    fi
    log "Hero upload route OK (${content_type})"
  else
    warn "No hero images on disk; skipped hero HTTP probe."
  fi
}

verify_upload_routes

log "PASS - /uploads/ is served from ${UPLOADS_DIR} on HTTP and API routes."
