#!/usr/bin/env bash
#
# Optimize the Byose Market production VPS:
#   - Apply tuned nginx site + snippets (gzip, keepalive, TLS, security headers)
#   - Harden common nginx globals (server_tokens)
#   - Raise process file limits for the API
#   - Reload nginx + PM2 and verify health/API latency
#
# Run on the VPS as root:
#   cd /root/byose-market && bash scripts/optimize-vps.sh
#   # legacy path still supported: /root/BYOSESEMARKET4
#
set -euo pipefail

if [[ -z "${DEPLOY_DIR:-}" ]]; then
  if [[ -d "/root/byose-market" ]]; then
    DEPLOY_DIR="/root/byose-market"
  elif [[ -d "/root/BYOSESEMARKET4" ]]; then
    DEPLOY_DIR="/root/BYOSESEMARKET4"
  else
    DEPLOY_DIR="/root/byose-market"
  fi
fi
WEB_ROOT="${WEB_ROOT:-/var/www/byosemarket}"
UPLOADS_DIR="${UPLOADS_DIR:-/var/lib/byosemarket/uploads}"
NGINX_SITE="${NGINX_SITE:-/etc/nginx/sites-available/byosemarket}"
NGINX_ENABLED="${NGINX_ENABLED:-/etc/nginx/sites-enabled/byosemarket}"
NGINX_SNIPPET_UPLOADS="${NGINX_SNIPPET_UPLOADS:-/etc/nginx/snippets/byosemarket-uploads.conf}"
NGINX_SNIPPET_STATIC="${NGINX_SNIPPET_STATIC:-/etc/nginx/snippets/byosemarket-static-assets.conf}"
PM2_APP_NAME="${PM2_APP_NAME:-byosemarket-api}"
API_PORT="${API_PORT:-5000}"
GITHUB_REPO_URL="${GITHUB_REPO_URL:-https://github.com/byosemarket-ui/byose-market.git}"

log() { printf '[optimize-vps] %s\n' "$*"; }
warn() { printf '[optimize-vps] WARNING: %s\n' "$*" >&2; }
fail() { printf '[optimize-vps] ERROR: %s\n' "$*" >&2; exit 1; }

remove_conflicting_byosemarket_sites() {
  local candidate
  shopt -s nullglob
  for candidate in /etc/nginx/sites-enabled/* /etc/nginx/conf.d/*.conf; do
    [[ "${candidate}" == "${NGINX_ENABLED}" ]] && continue
    if [[ -f "${candidate}" ]] && grep -Eq 'server_name[^;]*(byosemarket\.com|www\.byosemarket\.com)' "${candidate}"; then
      log "Removing stale Byose Market nginx config: ${candidate}"
      rm -f "${candidate}"
    fi
  done
  shopt -u nullglob
}

if [[ "${EUID}" -ne 0 ]]; then
  fail "Run as root: sudo bash scripts/optimize-vps.sh"
fi

[[ -d "${DEPLOY_DIR}" ]] || fail "Deploy directory not found: ${DEPLOY_DIR}"
cd "${DEPLOY_DIR}"

command -v nginx >/dev/null 2>&1 || fail "nginx is not installed"
command -v curl >/dev/null 2>&1 || fail "curl is not installed"

mkdir -p /etc/nginx/snippets "${WEB_ROOT}" /var/www/certbot
mkdir -p "${UPLOADS_DIR}/products" "${UPLOADS_DIR}/categories" "${UPLOADS_DIR}/users" "${UPLOADS_DIR}/reviews" "${UPLOADS_DIR}/hero" "${UPLOADS_DIR}/temp"
chmod -R u+rwX,go+rX "${UPLOADS_DIR}" || true

# ---------------------------------------------------------------------------
# Nginx site + snippets
# ---------------------------------------------------------------------------
log "Installing optimized nginx configs..."
install -m 644 "${DEPLOY_DIR}/deploy/nginx-byosemarket.conf" "${NGINX_SITE}"
install -m 644 "${DEPLOY_DIR}/deploy/nginx-snippet-static-assets.conf" "${NGINX_SNIPPET_STATIC}"

# Keep uploads alias dynamic so UPLOADS_DIR overrides still work.
cat > "${NGINX_SNIPPET_UPLOADS}" <<NGINX
# Generated by optimize-vps.sh / fix-vps-uploads-serving.sh
location ^~ /uploads/ {
    alias ${UPLOADS_DIR}/;
    access_log off;
    expires 30d;
    add_header Cache-Control "public, max-age=2592000, stale-while-revalidate=86400" always;
    add_header X-Content-Type-Options "nosniff" always;
    open_file_cache max=2000 inactive=60s;
    open_file_cache_valid 30s;
    open_file_cache_min_uses 2;
    open_file_cache_errors off;
    types {
        image/jpeg  jpg jpeg;
        image/png   png;
        image/webp  webp;
        image/gif   gif;
        image/avif  avif;
    }
    default_type application/octet-stream;
}
NGINX

ln -sfn "${NGINX_SITE}" "${NGINX_ENABLED}"
remove_conflicting_byosemarket_sites
rm -f /etc/nginx/sites-enabled/default

# Hide nginx version in responses when possible.
if [[ -f /etc/nginx/nginx.conf ]]; then
  if grep -qE '^\s*server_tokens\s+' /etc/nginx/nginx.conf; then
    sed -i 's/^\s*server_tokens\s\+.*/    server_tokens off;/' /etc/nginx/nginx.conf
  elif grep -qE '^\s*http\s*\{' /etc/nginx/nginx.conf; then
    sed -i '/^\s*http\s*{/a\    server_tokens off;' /etc/nginx/nginx.conf
  fi
fi

log "Testing nginx configuration..."
nginx -t
log "Reloading nginx..."
systemctl reload nginx

# ---------------------------------------------------------------------------
# Process / file limits for Node + nginx
# ---------------------------------------------------------------------------
log "Ensuring file descriptor limits..."
mkdir -p /etc/security/limits.d
cat > /etc/security/limits.d/byosemarket.conf <<'LIMITS'
* soft nofile 65535
* hard nofile 65535
root soft nofile 65535
root hard nofile 65535
LIMITS

mkdir -p /etc/systemd/system/nginx.service.d
cat > /etc/systemd/system/nginx.service.d/limits.conf <<'UNIT'
[Service]
LimitNOFILE=65535
UNIT

if systemctl list-unit-files | grep -q '^nginx.service'; then
  systemctl daemon-reload || true
fi

# Soft sysctl tuning for a small ecommerce VPS (safe defaults).
if [[ -w /etc/sysctl.d ]]; then
  cat > /etc/sysctl.d/99-byosemarket.conf <<'SYSCTL'
net.core.somaxconn = 1024
net.ipv4.tcp_fin_timeout = 15
net.ipv4.tcp_tw_reuse = 1
fs.file-max = 2097152
SYSCTL
  sysctl --system >/dev/null 2>&1 || warn "sysctl apply skipped (non-fatal)"
fi

# ---------------------------------------------------------------------------
# PM2 API process
# ---------------------------------------------------------------------------
if command -v pm2 >/dev/null 2>&1; then
  log "Reloading PM2 app (${PM2_APP_NAME}) with production env..."
  mkdir -p "${DEPLOY_DIR}/logs"
  pm2 startOrReload ecosystem.config.js --env production --update-env || pm2 reload ecosystem.config.js --env production --update-env
  pm2 save || true
else
  warn "pm2 not found — start API manually with: npm run pm2:start"
fi

# ---------------------------------------------------------------------------
# Publish critical root storefront assets (parity with upload fix script)
# ---------------------------------------------------------------------------
if [[ -d "${WEB_ROOT}" ]]; then
  log "Syncing root JS/CSS into ${WEB_ROOT}..."
  for file in "${DEPLOY_DIR}"/*.js; do
    [[ -f "${file}" ]] || continue
    base="$(basename "${file}")"
    if [[ "${base}" == "ecosystem.config.js" ]]; then
      continue
    fi
    cp -f "${file}" "${WEB_ROOT}/${base}"
  done
  for file in "${DEPLOY_DIR}"/*.css; do
    [[ -f "${file}" ]] && cp -f "${file}" "${WEB_ROOT}/$(basename "${file}")"
  done
fi

# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------
log "Verifying local health + product API..."
health_ok=0
for attempt in 1 2 3 4 5 6 7 8 9 10; do
  if curl -fsS --max-time 10 "http://127.0.0.1:${API_PORT}/healthz" >/dev/null; then
    health_ok=1
    break
  fi
  log "Local API /healthz not ready (attempt ${attempt}/10)..."
  sleep 2
done
[[ "${health_ok}" -eq 1 ]] || fail "Local API /healthz failed"
curl -fsS --max-time 10 "http://127.0.0.1/healthz" >/dev/null || fail "Nginx /healthz proxy failed"

PRODUCTS_HEADERS="$(mktemp)"
PRODUCTS_BODY="$(mktemp)"

# Prefer the direct Node listener first so deploy health is not blocked by the
# public HTTP→HTTPS redirect on port 80. Then confirm nginx still proxies /api.
HTTP_CODE="$(curl -sS -o "${PRODUCTS_BODY}" -D "${PRODUCTS_HEADERS}" -w "%{http_code}" \
  -H 'Accept-Encoding: gzip' \
  --max-time 20 \
  "http://127.0.0.1:${API_PORT}/api/products?limit=20&fields=card" || printf '000')"

if [[ "${HTTP_CODE}" != "200" ]]; then
  rm -f "${PRODUCTS_HEADERS}" "${PRODUCTS_BODY}"
  fail "Product API returned HTTP ${HTTP_CODE} on port ${API_PORT}"
fi

NGINX_PRODUCTS_CODE="$(curl -sS -o /dev/null -w "%{http_code}" \
  -H 'Accept-Encoding: gzip' \
  --max-time 20 \
  "http://127.0.0.1/api/products?limit=1&fields=card" || printf '000')"

if [[ "${NGINX_PRODUCTS_CODE}" != "200" ]]; then
  rm -f "${PRODUCTS_HEADERS}" "${PRODUCTS_BODY}"
  fail "Nginx product API proxy returned HTTP ${NGINX_PRODUCTS_CODE}"
fi

BYTES="$(wc -c < "${PRODUCTS_BODY}" | tr -d ' ')"
HAS_GZIP="$(awk 'tolower($1)=="content-encoding:" {print tolower($2)}' "${PRODUCTS_HEADERS}" | tr -d '\r' | head -n 1)"
HAS_CACHE="$(awk 'tolower($1)=="cache-control:" {print $0}' "${PRODUCTS_HEADERS}" | tr -d '\r' | head -n 1)"

log "Product API OK (HTTP 200, body=${BYTES} bytes)"
log "Content-Encoding: ${HAS_GZIP:-none}"
log "Cache-Control: ${HAS_CACHE:-none}"

rm -f "${PRODUCTS_HEADERS}" "${PRODUCTS_BODY}"

if command -v pm2 >/dev/null 2>&1; then
  pm2 describe "${PM2_APP_NAME}" >/dev/null 2>&1 && pm2 list || true
fi

log "PASS - VPS nginx/PM2 optimizations applied and verified."
